version: "2"
services:
  nginx:
    image: nginx:1-alpine
    volumes:
      - ./vhost.d:/etc/nginx/vhost.d
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy_net

  nginx-gen:
    image: jwilder/docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx
    command: "-notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    networks:
      - proxy_net
      
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    volumes_from: 
      - nginx
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

networks:
  proxy_net:
    driver: bridge

